spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          - prometheus
weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${WEATHER_STACK_API_KEY:default-key}
  api-call-limit: 30
  cache-name: weathers
  cache-ttl: 10000
